# Generated by Django 6.0.5 on 2026-06-23 22:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['team__team_name', 'shirt_number']},
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FR', 'Forward'), ('UK', 'Unknown')], default='UK', max_length=2),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='main_shirt_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('main_shirt_number__gte', 1), ('main_shirt_number__lte', 99)), name='player_main_shirt_number_between_1_and_99'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('team_name', 'sport_name'), name='team_name_sport_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'player'), name='team_player_unique'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'shirt_number'), name='shirt_number_unique_per_team'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.CheckConstraint(condition=models.Q(('shirt_number', 1), ('shirt_number', 99)), name='team_main_shirt_number_between_1_and_99'),
        ),
    ]
