# Generated by Django 6.0.5 on 2026-06-24 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teammember',
            name='team_main_shirt_number_between_1_and_99',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.CheckConstraint(condition=models.Q(('shirt_number__gte', 1), ('shirt_number__lte', 99)), name='team_main_shirt_number_between_1_and_99'),
        ),
    ]
