# Generated by Django 6.0.5 on 2026-06-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_teammember_team_main_shirt_number_between_1_and_99_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
