# Generated by Django 6.0.5 on 2026-06-26 22:21

import apps.teams.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_logo_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to=apps.teams.models.team_logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
