# Generated by Django 6.0.5 on 2026-06-25 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_options_match_created_at'),
        ('tournaments', '0002_tournament_teams_delete_tournamentmatch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_matches', to='tournaments.tournament'),
            preserve_default=False,
        ),
    ]
