# Generated by Django 6.0.5 on 2026-06-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_rename_date_match_scheduled_date_match_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=100),
        ),
    ]
