# Generated by Django 6.0.5 on 2026-06-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
    ]
