# Generated by Django 6.0.5 on 2026-06-27 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_stadium_match_stadium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='location',
        ),
    ]
