# Generated by Django 6.0.5 on 2026-06-27 01:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_remove_match_location'),
        ('teams', '0005_alter_team_logo_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('fouls', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('red_cards', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1)])),
                ('extra_statistics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_match_statistics', to='teams.team')),
            ],
            options={
                'ordering': ['match', 'team__team_name', 'player__surname'],
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='unique_player_statistics_per_match')],
            },
        ),
    ]
