# Generated by Django 6.0.5 on 2026-06-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_teammember_team_main_shirt_number_between_1_and_99_and_more'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='tournamentParticipation', to='teams.team'),
        ),
        migrations.DeleteModel(
            name='TournamentMatch',
        ),
    ]
