# Generated by Django 6.0.5 on 2026-06-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_teammember_team_main_shirt_number_between_1_and_99_and_more'),
        ('tournaments', '0002_tournament_teams_delete_tournamentmatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Ongoing', 'Ongoing')], default='Scheduled', max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournamentParticipation', to='teams.team'),
        ),
    ]
