# Generated by Django 6.0.5 on 2026-06-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_logo_img'),
        ('tournaments', '0003_alter_tournament_status_alter_tournament_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('request_answered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tournament',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='tournament_end_after_start'),
        ),
        migrations.AddField(
            model_name='tournamentparticipation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='teams.team'),
        ),
        migrations.AddField(
            model_name='tournamentparticipation',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='tournaments.tournament'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipation',
            constraint=models.UniqueConstraint(fields=('tournament', 'team'), name='tournament_participation_unique'),
        ),
    ]
